### ISSUE TITLE
Is it like vue templates?

### ISSUE THREAD

**Issue by rohmanhm** [simonrelet/react-html-template-loader#3]
Is this inspired from vue templates syntax?
If yes, maybe you can put in your README file. So it's more describable.

**Comment by simonrelet** [comment]
Hi, I didn't have Vue in mind when I wrote the template syntax, I wanted it to look like web-components but it probably has parts of several existing syntaxes. Either way it's a bit _custom_ so that's why there are no "inspired by" in the README.

**Comment by rohmanhm** [comment]
First I thought this plugin like what make React JSX like Vue Template syntax.

Thanks.
That answered my question 😃 .
